#!/usr/bin/env bash
# Regenerates docs/structure.md from the current file tree, respecting .gitignore.
# Runs automatically via the pre-commit hook (.githooks/pre-commit, enabled with
# `./scripts/dev.sh setup`); can also be run by hand. Output is deterministic — no
# timestamp, repo-relative root — so the file only changes when the tree changes.
# Usage: ./scripts/update-structure.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$ROOT/docs/structure.md"

cd "$ROOT"

{
  echo "# Project structure"
  echo
  echo "_Generated by \`scripts/update-structure.sh\` (pre-commit hook) — do not edit by hand._"
  echo
  echo '```'
  tree --gitignore --dirsfirst -a -I '.git' .
  echo '```'
} > "$OUTPUT"

echo "Updated: $OUTPUT"
